server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.realks.win/tw555demo
    username: tw555demo
    password: tw555demo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




